#pragma once

enum ServerDisconnectIdentifiers {
	UNKNOWN_SERVER_ERROR = 0,
	DUPLICATE_LOGIN = 4,
	SERVER_SHUTDOWN = 5,
	SERVER_MAP_LOAD_FAILURE = 6,
	INVALID_SESSION_KEY = 7,
	ACCOUNT_NOT_IN_PENDING_LIST = 8,
	CHARACTER_NOT_FOUND = 9,
	CHARACTER_CORRUPTED = 10,
	KICK = 11,
	FREE_TRIAL_EXPIRED = 12,
	PLAY_SCHEDULE_TIME_DONE = 13
};

enum CONNECTION_TYPE {
	CONN_SERVER = 0,
	CONN_AUTH,
	CONN_CHAT,
	CONN_UNKNOWN,
	CONN_WORLD,
	CONN_CLIENT
};

enum SERVER {
	MSG_SERVER_VERSION_CONFIRM = 0,
	MSG_SERVER_DISCONNECT_NOTIFY,
	MSG_SERVER_GENERAL_NOTIFY
};

enum AUTH {
	MSG_AUTH_LOGIN_REQUEST = 0,
	MSG_AUTH_LOGOUT_REQUEST,
	MSG_AUTH_CREATE_NEW_ACCOUNT_REQUEST,
	MSG_AUTH_LEGOINTERFACE_AUTH_RESPONSE,
	MSG_AUTH_SESSIONKEY_RECEIVED_CONFIRM,
	MSG_AUTH_RUNTIME_CONFIG
};
